In [2]:
import numpy as np

In [3]:
lst = [1., 2, 3, 4, 5, 6]
arr = np.array(lst)
print(arr)
print(arr.shape)

[1. 2. 3. 4. 5. 6.]
(6,)


In [4]:
lst2 = np.array([[1, 2, 3], [3, 4, 5]])
print(lst2)
print(lst2.shape)
print(type(lst2))

[[1 2 3]
 [3 4 5]]
(2, 3)
<class 'numpy.ndarray'>


In [5]:
mat = np.matrix(lst2)
print(mat)
print(type(mat))

[[1 2 3]
 [3 4 5]]
<class 'numpy.matrix'>


In [6]:
arr1 = np.arange(16)
arr2 = np.reshape(arr1, (8, -1))
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


### Deep Copy

In [7]:
arr1 = np.arange(12)
arr2 = arr1.reshape(2, -1)
arr3 = arr1[2:10]
arr4 = arr2.copy()

In [8]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
arr2[0, 0] = 4

In [10]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[ 4  1  2  3  4  5  6  7  8  9 10 11]
[[ 4  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [11]:
arr = np.arange(12)
arr5 = np.reshape(arr, (3, -1))
print(arr5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
a = arr5.sum(axis=0)
print(a)

[12 15 18 21]


In [13]:
b = arr5.sum(axis=1)
print(b)

[ 6 22 38]


In [14]:
print(np.argmax(b))
print(np.argmin(b))

2
0


In [15]:
print(np.argmax(a))
print(np.argmin(a))

print(np.argmax(arr5))
print(np.argmin(arr5))

3
0
11
0


In [16]:
arr6 = np.array([2, 4, 1, 2, 7, 0, 34, 8])
print(np.argmax(arr6))
print(np.argmin(arr6))

6
5


In [17]:
a = np.random.rand(2, 3, 4)
print(a)

[[[0.4247431  0.76689363 0.84507838 0.77260946]
  [0.3291811  0.15812013 0.51841293 0.47906924]
  [0.51115862 0.32713192 0.14643367 0.63363335]]

 [[0.89272619 0.68395829 0.37594136 0.54447005]
  [0.28931031 0.98142139 0.86198872 0.93111953]
  [0.57498675 0.54791686 0.039434   0.59736756]]]


In [18]:
print(a[:, np.newaxis, :, :].shape)

(2, 1, 3, 4)


In [19]:
print(a[..., np.newaxis].shape)

(2, 3, 4, 1)


In [20]:
print(a[:, np.newaxis].shape)

(2, 1, 3, 4)


In [21]:
y = np.array([[1, 2], [3, 4]])
print(np.repeat(y, 3, axis=0))
print(np.repeat(y, 3, axis=1))

[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]


In [22]:
a1 = np.random.rand(5, 4)
print(a1)

[[0.33692544 0.68697572 0.23894837 0.25313206]
 [0.12755369 0.79565927 0.54625202 0.35793299]
 [0.44813463 0.66597609 0.09403172 0.34585666]
 [0.32947151 0.20811305 0.2731209  0.58930752]
 [0.94438299 0.06264861 0.16770657 0.01668416]]


In [23]:
print(a1.shape)

(5, 4)


In [24]:
arr1 = np.arange(12)
arr2 = arr1.reshape(2, -1)
arr3 = arr1[0:10]
arr4 = arr2.copy()

arr2[0, 0] = 10

In [25]:
print(arr1)
print(arr2)
print('arr1 메모리 공간을 가리키고 있음:', arr3)
print('arr2와 다른 공간을 가리키고 있음:\n', arr4)

[10  1  2  3  4  5  6  7  8  9 10 11]
[[10  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr1 메모리 공간을 가리키고 있음: [10  1  2  3  4  5  6  7  8  9]
arr2와 다른 공간을 가리키고 있음:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [32]:
a = np.arange(12)
b = a.reshape(2, -1)
c = a[0:10]
d = a.copy()

print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [34]:
b[0][0] = 10

In [35]:
print(a)
print(b)
print(c)
print(d)

[10  1  2  3  4  5  6  7  8  9 10 11]
[[10  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[10  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
