## 9월 12일 Numpy

In [1]:
import numpy as np

In [2]:
lst = [95., 90., 90., 70, 92, 88, 80]

In [3]:
print(lst)
print(len(lst))
print(type(lst))
print(type(lst[0]))
print(type(lst[4]))

[95.0, 90.0, 90.0, 70, 92, 88, 80]
7
<class 'list'>
<class 'float'>
<class 'int'>


In [4]:
arr = np.array(lst)

In [5]:
print(arr)
print(arr.shape)
print(type(arr))
print(arr.dtype)

[95. 90. 90. 70. 92. 88. 80.]
(7,)
<class 'numpy.ndarray'>
float64


In [6]:
lst1 = [[95, 90], [70, 92]]
lst2 = [[90, 5], [4, 2]]

# 넘파이 리스트
arr1 = np.array(lst1, dtype=np.int32)
arr2 = np.array(lst2)
print(np.matmul(arr1, arr2))        # 행렬끼리의 곱
print(np.multiply(arr1, arr2))      # 원소끼리의 곱 

# 행렬로 변환간 경우
arr3 = np.matrix(lst1)
arr4 = np.matrix(lst2)
print(arr3 @ arr4)          # 행렬끼리의 곱
print(arr3 * arr4)          # 행렬끼리의 곱

[[8910  655]
 [6668  534]]
[[8550  450]
 [ 280  184]]
[[8910  655]
 [6668  534]]
[[8910  655]
 [6668  534]]


In [7]:
arr1 = np.arange (12)
arr2 = arr1. reshape (2, -1)
print (arr1)
print (arr2)

print (arr1[0])
print (arr2[0])

print (arr2[0, 0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
0
[0 1 2 3 4 5]
0


In [8]:
# Deep Copy
arr1 = np.arange (12)
arr2 = arr1.reshape (2, -1)
arr3 = arr1[2:10]
arr4 = arr2.copy()

arr2[0, 0] = 0

print (arr1)
print (arr2)
print (arr3)
print (arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
# Indexing
arr1 = np.arange(16)
arr2 = arr1.reshape(4, -1)
print(arr2)

print(arr2[1, 3])
print(arr2[0, 1])
print(arr2[2, 2])

print(arr2[[1, 0, 2], [3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7
1
10
[ 7  1 10]


In [10]:
arr = np.arange(16).reshape(4, 4)
print(arr)
print(arr[1:3, 1:3])
print(arr[:, :])
print(arr[1:, :-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
