In [2]:
import numpy as np

In [3]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
c = np.array([0.0, 10.0, 20.0, 30.0])
d = np.array([1.0, 2.0, 3.0])
print(a[:, np.newaxis] + b)

### repeat

In [ ]:
x = np.array([1, 2, 3])
y = np.array([[1, 2], [3, 4]])

print(np.repeat(x, 3))
print(np.repeat(y, 3))

print(np.repeat(y, 3, axis=0))
print(np.repeat(y, 3, axis=1))

In [5]:
x = np.array([1, 2, 3])
y = np.array([[1, 2], [3, 4]])

print(np.repeat(x, 3))
print(np.tile(x, 3))

print(np.tile(y, [1, 1]))
print(np.tile(y, [2, 1]))
print(np.tile(y, [1, 3]))
print(np.tile(y, [2, 4]))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


## stack

In [6]:
a1 = np.random.rand(5, 100)
a2 = np.random.rand(5, 100)
a3 = np.random.rand(5, 100)

a_stack = np.stack([a1, a2, a3])

a_stack_0 = np.stack([a1, a2, a3], axis=0)
a_stack_1 = np.stack([a1, a2, a3], axis=1)
a_stack_2 = np.stack([a1, a2, a3], axis=2)
a_stack_m = np.stack([a1, a2, a3], axis=-1)

print(a_stack.shape)
print(a_stack_0.shape)
print(a_stack_1.shape)
print(a_stack_2.shape)
print(a_stack_m.shape)

(3, 5, 100)
(3, 5, 100)
(5, 3, 100)
(5, 100, 3)
(5, 100, 3)


## concatenate

In [8]:
v1 = np.random.rand(10, 4, 3)
v2 = np.random.rand(20, 4, 3)
v3 = np.random.rand(30, 4, 3)

h1 = np.random.rand(5, 10, 3)
h2 = np.random.rand(5, 20, 3)
h3 = np.random.rand(5, 30, 3)

vstack0 = np.vstack([v1, v2, v3])
concat0 = np.concatenate([v1, v2, v3], axis=0)

hatack1 = np.hstack([h1, h2, h3])
concat1 = np.concatenate([h1, h2, h3], axis=1)

print(vstack0.shape)
print(concat0.shape)
print(hatack1.shape)
print(concat1.shape)

(60, 4, 3)
(60, 4, 3)
(5, 60, 3)
(5, 60, 3)
