In [2]:
import numpy as np

In [3]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
c = np.array([0.0, 10.0, 20.0, 30.0])
d = np.array([1.0, 2.0, 3.0])
print(a[:, np.newaxis] + b)

### repeat

In [4]:
x = np.array([1, 2, 3])
y = np.array([[1, 2], [3, 4]])

print(np.repeat(x, 3))
print(np.repeat(y, 3))

print(np.repeat(y, 3, axis=0))
print(np.repeat(y, 3, axis=1))

[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
