In [1]:
import numpy as np

In [3]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
c = np.array([0.0, 10.0, 20.0, 30.0])
d = np.array([1.0, 2.0, 3.0])
print(a[:, np.newaxis] + b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
