## 9월 19일

In [1]:
import numpy as np

In [3]:
a = [400, 500, 600, 500, 300, 500, 700, 400, 700]
b = [500, 700, 700, 300, 400, 600, 900, 200, 900]
a = np.reshape(a, (3, 3))
b = np.reshape(b, (3, 3))
print(a)
print(b)

[[400 500 600]
 [500 300 500]
 [700 400 700]]
[[500 700 700]
 [300 400 600]
 [900 200 900]]


In [7]:
# Array Indexing(1)
print(a[0, 1])
print(a[0:2, :])
print(a[:, : -1])

500
[[400 500 600]
 [500 300 500]]
[[400 500]
 [500 300]
 [700 400]]


In [8]:
# Array Indexing(2)
c = a[[0, 2], :]
d = a[(0, 2), :]
print(c)
print(d)

[[400 500 600]
 [700 400 700]]
[[400 500 600]
 [700 400 700]]


In [11]:
# Max, Min, Mean
print(a.max(), b.max())         # 각각의 행렬에 대한 최댓값
print(np.maximum(a.max(), b.max())) # 가진 것중에 더 큰 값

print(a.min(), b.min())
print(np.minimum(a.min(), b.min()))

print(a.mean(), b.mean())
print((a.mean() + b.mean()) / 2)

700 900
900
300 200
200
511.1111111111111 577.7777777777778
544.4444444444445


In [12]:
# axis(1)
a.sum(axis=0)   # 행 방향으로 더하라

array([1600, 1200, 1800])

In [14]:
# axis(2)
a.sum(axis=1)

array([1500, 1300, 1800])

In [16]:
# con.
print(a.max(axis=0), b.max(axis=0))
print(a.max(axis=1), b.max(axis=1))

[700 500 700] [900 700 900]
[600 500 700] [700 600 900]


In [18]:
# argmax
print(a - b)
print(np.abs(a - b))

[[-100 -200 -100]
 [ 200 -100 -100]
 [-200  200 -200]]
[[100 200 100]
 [200 100 100]
 [200 200 200]]
